# Generated by Django 5.1 on 2024-08-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Account_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Account_detail',
            },
        ),
        migrations.CreateModel(
            name='Account_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Account_name',
            },
        ),
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Account_type',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=True)),
                ('tier', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('tier', models.IntegerField()),
                ('jan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('may', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jun', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jul', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aug', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nov', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('selected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Payee',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_detail', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('tier', models.IntegerField()),
                ('year6', models.DecimalField(decimal_places=2, max_digits=14)),
                ('year5', models.DecimalField(decimal_places=2, max_digits=14)),
                ('year4', models.DecimalField(decimal_places=2, max_digits=14)),
                ('year3', models.DecimalField(decimal_places=2, max_digits=14)),
                ('year2', models.DecimalField(decimal_places=2, max_digits=14)),
                ('year1', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
