# Generated by Django 5.1.4 on 2025-10-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
