# Generated by Django 5.1.4 on 2025-10-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_money', '0002_alter_payee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.CharField(max_length=20)),
                ('transaction', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('acc_pre_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('acc_post_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('crypto_pre_bal', models.DecimalField(decimal_places=8, max_digits=18)),
                ('crypto_post_bal', models.DecimalField(decimal_places=8, max_digits=18)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purchase_qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('spare_char1', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_char2', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_dec1', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('spare_dec2', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'CryptoPurchase',
            },
        ),
    ]
