# Generated by Django 5.1.4 on 2025-10-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_money', '0003_cryptopurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('acc_no', models.CharField(max_length=20)),
                ('order_no', models.CharField(max_length=20, unique=True)),
                ('side', models.CharField(max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('spare_char1', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_char2', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_char3', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_dec1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spare_dec2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spare_dec3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'stock_purchase',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AlterModelOptions(
            name='cryptopurchase',
            options={'managed': False},
        ),
    ]
