# Generated by Django 5.1.4 on 2025-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_money', '0004_stockpurchase_alter_cryptopurchase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('acc_no', models.CharField(max_length=20)),
                ('order_no', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('brokerage_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('trading_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('clearing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spare_char1', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_char3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'stock_purchased',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.DeleteModel(
            name='StockPurchase',
        ),
    ]
