# Generated by Django 5.1.4 on 2025-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_money', '0005_stockpurchased_delete_stockpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.CharField(max_length=20)),
                ('transaction', models.CharField(max_length=50)),
                ('timestamps', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('side', models.CharField(max_length=20)),
                ('acc_post_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('crypto_post_bal', models.DecimalField(decimal_places=8, max_digits=18)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purchase_qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('fear_greed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('spare_char1', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_dec2', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'BinanceTransaction',
            },
        ),
        migrations.CreateModel(
            name='CryptoAccumulatedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.CharField(max_length=20)),
                ('accumulated_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=30, null=True)),
                ('spare1', models.CharField(blank=True, max_length=100, null=True)),
                ('spare2', models.CharField(blank=True, max_length=100, null=True)),
                ('spare3', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('spare4', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'CryptoAccumulatedAmount',
            },
        ),
        migrations.CreateModel(
            name='CryptoSymbolStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.CharField(max_length=20)),
                ('buy_status', models.BooleanField(default=False)),
                ('sell_status', models.BooleanField(default=False)),
                ('zone_color', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=30, null=True)),
                ('spare1', models.CharField(blank=True, max_length=100, null=True)),
                ('spare2', models.CharField(blank=True, max_length=100, null=True)),
                ('spare3', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('spare4', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'CryptoSymbolStatus',
            },
        ),
    ]
